### PR TITLE
nerdamer.factor('4677271')

### PR DESCRIPTION
**Pull request by Yaffle**
It is a fix for https://github.com/jiggzson/nerdamer/issues/438

P.S. I am not an expert here, but, seems, it works.

### CODE REVIEW

**Comment by jiggzson** [comment]
@Yaffle, thanks a lot for taking care of this! I have some working changes on the `dev` branch which is normally the branch I commit to during development but this is a somewhat important bug fix and that branch is currently failing. Let me review those changes and if needed would it be too much trouble to target that branch instead? Thanks again.

**Comment by jiggzson** [comment]
@Happypig375, if you're referring to `rho(c + 1)`, he casts it to a `bigInt` at the top of the rho function.

**Comment by Yaffle** [comment]
@jiggzson,
> Let me review those changes and if needed would it be too much trouble to target that branch instead?
Hm..... not sure what should I do.... wait or create a pull request to the branch.

@jiggzson , in fact, `bigInt` library is saying, that it is better to use it without `new`.

**Comment by jiggzson** [comment]
@Yaffle, no need to do anything. Factoring is somewhat a critical function so bugs in the factor function affect quite a few other functions. I'll just pull the changes into the `dev` branch. The changes that I currently have on `dev` are nice-to-have changes. Besides it currently has failing tests which tends to confuse things. I'll close this PR over the weekend.
>@jiggzson , in fact, `bigInt` library is saying, that it is better to use it without `new`.

What @Happypig375 was concerned about was that you were converting a `bigInt` back to a native JavaScript `Number`. I was just pointing out that that wasn't the case and that the argument was an `int` which was converted to a `bigInt` at the beginning of the `rho` function. Sorry for the confusion.

**Pull request merged**
