### PR TITLE
Implement #329

### PR DESCRIPTION
**Pull request by Happypig375**

### CODE REVIEW

**Comment by Happypig375** [comment]
A few lcm tests are wrong, will come back to that later.

**Comment by Happypig375** [comment]
Things to do:
- [ ] Fix LCM wrong result bugs
- [ ] GCD Simplification
   - gcd(6,a,12) => gcd(a,6)
   - gcd(a,b,a^2) => gcd(a,b)
- [ ] GCD flattening
   - gcd(a,gcd(b,c)) => gcd(a,b,c)

**Comment by jiggzson** [comment]
Place the failing tests in their own spec and just xit them.

**Comment by Happypig375** [comment]
No more time today, @jiggzson please check the changes and merge + edit tests if neccessary.

**Comment by Happypig375** [comment]
My English:sweat:
>please check the changes and merge + edit tests if neccessary

Claification: ~~if necessary~~ if you think the current implementation is good enough.

**Comment by Happypig375** [comment]
Wait no, just noticed the 7710 line change in Algebra.js. Will open a new PR tomorrow.

**Comment by jiggzson** [comment]
>Wait no, just noticed the 7710 line change in Algebra.js. Will open a new PR tomorrow.

You don't have to. Just fix this one. I'm seeing the entire contents of nerdamer.core.js in Algebra.js.

I noticed your todo list on the bottom of the PR yesterday which is why I asked you to place failing tests in their own spec. And just to be clear, I meant newly added failing tests, not existing ones that are not failing.

**Comment by Happypig375** [comment]
To this point, all lcm bugs should only be gcd bugs.
This lcm algorithm is pretty good, I should say.

**Comment by Happypig375** [comment]
Oooooooooooh LOOK 👀 
Wolfram Alpha also cannot simplify this!!!
(3+x^3)^2*(6*x^3+x^6+9)^(-1)
😆

**Comment by jiggzson** [comment]
I'm still showing the tests as failing. I'll take a look at which ones. Hopefully I get a chance to do so today.

**Comment by Happypig375** [comment]
By gcd, it includes my gcd implementation and your original one.
I plan on revising this tomorrow or 2 days later.

**Comment by Happypig375** [comment]
http://www.wolframalpha.com/input/?i=gcd(x%5Ey,x%5E(y%2Bz),x%5Ez)
http://www.wolframalpha.com/input/?i=gcd(x%5Ey,x%5E(y-z),x%5Ez)
Weird...

**Comment by Happypig375** [comment]
TODO: gcd(x^(2x),(2x)^x) => 2^x*x^x should=> x^x

**Comment by Happypig375** [comment]
TODO: gcd(1/a/b,1/b/c) => b should=> b^(-1)

**Comment by Happypig375** [comment]
The above two bugs seem to originate from the original gcd code. @jiggzson Can you check?

**Comment by Happypig375** [comment]
(See CI build)
One of the tests require (3+x^3)^2*(6*x^3+x^6+9)^(-1) => 1. Hmm... Can't use Algebra.divide here because a gcd symfunction may be the divisor (will throw expected polynomial). Any thoughts?

**Comment by Happypig375** [comment]
A look at failing tests:

`Expected 'DONE*NOT*YET' to equal 'FAIL THIS TEST'.`
Will remove when done.

`Expected '(1375*x^9+1430*x^8+1872*x^6+37550*x^7+47075*x^5+7150*x^12+7510*x^3+9360*x+9360*x^10)*(361*x^7+473*x^5+5*x^11+72*x^3+90*x^9+91*x)*(5*x^6+x^2)^(-1)*x' to equal '(1375*x^9+1430*x^8+1872*x^6+37550*x^7+47075*x^5+7150*x^12+7510*x^3+9360*x+9360*x^10)*(361*x^7+473*x^5+5*x^11+72*x^3+90*x^9+91*x)'`
This test was wrong. It needs to be updated to reflect the right answer.

`Expected '(12*x^3+12*x^4+3*x^5+4*x^6+4*x^7+x^8)*(3+x^3)^2*(6*x^3+x^6+9)^(-1)' to equal '(12*x^3+12*x^4+3*x^5+4*x^6+4*x^7+x^8)*(3+x^3)'`
(3+x^3)^2*(6*x^3+x^6+9)^(-1) needs to cancel out. Hmm... Can't use Algebra.divide here because a gcd symfunction may be the divisor (will throw expected polynomial). Any thoughts? Also, update the test to reflect the right answer.

`Expected 'a^(-1)' to equal 'a^(-1)*b^(-1)*c^(-1)*gcd(a^(-1)*b^(-1),a^(-1)*c^(-1),b^(-1)*c^(-1))^(-1)'.`
aka TODO: gcd(1/a/b,1/b/c) => b should=> b^(-1).

**Comment by Happypig375** [comment]
See TODO in tests for things left to do.
Also, Wolfram Alpha does not do the GCD Simplification thing, so I think I will not do that item.

**Comment by jiggzson** [comment]
>One of the tests require (3+x^3)^2*(6*x^3+x^6+9)^(-1) => 1. Hmm... Can't use Algebra.divide here because a gcd symfunction may be the divisor (will throw expected polynomial). Any thoughts?

One idea I had is to take the denominator of each and store them, get the gcd of the numerators and put back the denominators. I'm not sure if you need to take the gcd or the lcm of denominators before putting back the denominator. I was hoping to do some more research on this.

>The above two bugs seem to originate from the original gcd code. @jiggzson Can you check?

I'm assuming you mean the error pertaining to gcd of group EX but those aren't supported in the original gcd function. It seems like you've done some work to support these so does this message still apply?

**Comment by Happypig375** [comment]
> I was hoping to do some more research on this.

Was that about divide or was that about gcd?
> It seems like you've done some work to support these so does this message still apply?

`nerdamer("(2x)^x").symbol.group` returns 7, which is group CB. It won't be processed by my code that checks for EX.

**Comment by Happypig375** [comment]
`nerdamer("1/a").symbol.group` => 3
It is group S.
`nerdamer.getCore().Algebra.gcd_(nerdamer("1/a").symbol,nerdamer("1/b").symbol)` => a^(-1)*b^(-1)
It is a bug in the original gcd code too.

**Comment by jiggzson** [comment]
>`nerdamer("(2x)^x").symbol.group` returns 7, which is group CB. It won't be processed by my code that checks for EX.

Yes. If you console.log the result you'll see that the output is **2^x*x^x** which is indeed group CB

> `nerdamer.getCore().Algebra.gcd_(nerdamer("1/a").symbol,nerdamer("1/b").symbol)` => a^(-1)*b^(-1)

Yes that's what I was talking earlier when I was talking about storing the denominators. Also you don't have to call nerdamer(expression). This would work too.

```javascript
var core = nerdamer.getCore();
//I prefer to store the parser in _ since it makes it easier to read
var _ = nerdamer.PARSER; 
var gcd = core.Algebra.gcd(_.parse('1/a'), _.parse('1/b'));
```

**Comment by Happypig375** [comment]
>Yes that's what I was talking earlier when I was talking about storing the denominators

I am thinking of getDenom(). Is that safe to call? Do I only have to check for group S or do this for all symbols?

**Comment by jiggzson** [comment]
getDenom is safe to call on all object of the Symbol class. You can check if it is a symbol by using **core.Utils.isSymbol**. If you find a bug then let's fix it. I'm thinking of making this function external at some point (similar to coeffs) so I guess now is as good a time as any to start polishing it up.

**Comment by Happypig375** [comment]
>Do I only have to check for group S or do this for all symbols?

Oops, I meant is the action of storing the denominators only applicable to the symbols in group S?

**Comment by jiggzson** [comment]
**getDenom** is applicable to symbols of all groups. I don't think it includes the denominator of the multiplier when returning the denominator. This is because the multiplier is typically treated separately so if you need to include it you'd have to grab it yourself.

**Comment by Happypig375** [comment]
Ok, will try using it.
Basically the new gcd is now this:
(original gcd of multiplier)*(original gcd of numerator)/(original gcd of denominator)

Got it.

**Comment by jiggzson** [comment]
>(original gcd of multiplier)*(original gcd of numerator)/(original gcd of denominator)

I would verify that this is correct. You may have to hunt a little for this information but it's out there.

**Comment by Happypig375** [comment]
```js
var core = nerdamer.getCore();
var _ = core.PARSER;
var __ = core.Algebra;
var symbol = _.parse("1/a*1/b");
var num, denom;
document.writeln(num = symbol.getNum()); //1
document.writeln(denom = symbol.getDenom()); //a^(-1)*b^(-1)
document.writeln(__.gcd_(num,denom)); //a^(-1)*b^(-1)
```
getDenom() is not helping here.

**Comment by Happypig375** [comment]
lcm(1/a,1/b,1/c):
I got the root cause pinned down to __.gcd_(_.parse("a^(-1)*b^(-1)"),_.parse("a^(-1)*c^(-1)")) => a

**Comment by Happypig375** [comment]
Even more pinned down:
```js
        gcd_: function(a, b) { 
            if(a.group === FN || a.group === P)
                a = core.Utils.block('PARSE2NUMBER', function() {
                   return _.parse(a); 
                });
		
            if(b.group === FN)
                b = core.Utils.block('PARSE2NUMBER', function() {
                   return _.parse(b); 
                });
		
            if(a.isConstant() && b.isConstant()) { 
                // return core.Math2.QGCD(new Frac(+a), new Frac(+b));
                return new Symbol(core.Math2.QGCD(new Frac(+a), new Frac(+b)));
            }
        document.writeln(a,'.....',b); //a^(-1)*b^(-1).....a^(-1)*c^(-1)
		
            var den = _.multiply(a.getDenom() || new Symbol(1), b.getDenom() || new Symbol(1)).invert();
            a = _.multiply(a.clone(), den.clone());
            b = _.multiply(b.clone(), den.clone());
		
        document.writeln(a,'.....',b); //a*c.....a*b
```

**Comment by jiggzson** [comment]
>lcm(1/a,1/b,1/c):
I got the root cause pinned down to __.gcd_(_.parse("a^(-1)*b^(-1)"),_.parse("a^(-1)*c^(-1)")) => a should=> a^(-1)

Exactly. We already agreed that the lcm issue has to do with how gcd deals with denominators.  This was the reason for this:
>(original gcd of multiplier)*(original gcd of numerator)/(original gcd of denominator)

As a correction, I think you meant multipliers, numerators, and denominators (plural). Correct?

**Comment by Happypig375** [comment]
@jiggzson 
```js
var core = nerdamer.getCore();
var _ = core.PARSER;
var __ = core.Algebra;
var symbol1 = _.parse("15");
var symbol2 = _.parse("21");
document.writeln(__.gcd_(symbol1,symbol2)); //3
document.writeln(__.gcd_(symbol1,symbol2.distributeExponent())); //15
```
What is going on?
This causes a lot of unit tests to fail.

Also, when should clone() be used?
This method seems to be spammed everywhere, which makes me wonder is it necessary.

**Comment by jiggzson** [comment]
Yes, clone is ugly, irritating,  but unfortunately necessary. I can give you the justification for why it still exists and why all my previous attempts to reduce/remove if have been unsuccessful. It's really a trade-off to minimize computations at the lower level and pay the price at the higher level. This is why functions such as factor complete in the time that it does. BigIntegers, clone, and all these other wrappers are just the price for doing math with JavaScript. When in doubt, call clone.

**Comment by Happypig375** [comment]
So not doing auto-cloning speeds up computation, eh?
Ok...

**Comment by Happypig375** [comment]
There really should be documentation on when to clone and when cloning can be omitted.
As far as I can see, only methods in symbol and the add, subtract, multiply and divide mutates the symbol. Is this all?

**Comment by jiggzson** [comment]
There kind of is in the "Digging deeper" and the "Extending the core" sections on the site. I hope to some day find a clean auto-clone solution. Auto-cloning is easy when dealing with numbers but when you're adding or multiplying long expressions which don't simplify and you're constantly calling clone, you start to notice the difference almost right away. On the user's end this difference can be ignored. I don't have that luxury inside of the library itself.

>As far as I can see, only methods in symbol and the add, subtract, multiply and divide mutates the symbol. Is this all?

Don't forget pow

**Comment by Happypig375** [comment]
Like this:
"Methods of the Symbol class, add, subtract, multiply, divide and pow methods of the Parser mutates the symbol. Call clone() if mutating is not wanted."
Looks good.

**Comment by Happypig375** [comment]
@jiggzson More information:
Before 1ecaa42610ea98ab737097267a0be27790b495bc , only 1 test fail
After 1ecaa42610ea98ab737097267a0be27790b495bc , a lot of tests fail because https://github.com/jiggzson/nerdamer/pull/337#issuecomment-353816129

I will be on a time crunch too. I might return to this on early January.

(P.S. Unusual time of reply, it is 4:05AM for me right now (+0800), but because I am camping I stood up late)

**Comment by jiggzson** [comment]
Well thanks for the quick reply. Can you close off the two open PR's and reopen this one at a later time? For some reason Github gives me grief when trying to merge with open PR's on the branch. Enjoy your camping trip.

**Comment by Happypig375** [comment]
Bye bye most commennted issue/PR of all time :cry:

**Comment by Happypig375** [comment]
Wanted to restart this, but bumped with merge conflicts 😠

**Comment by Happypig375** [comment]
Merge conflicts done!!!

**Comment by jiggzson** [comment]
Can you pull the changes? I forgot to open this.

**Comment by Happypig375** [comment]
>Can you pull the changes? 

Can you elaborate?
>I forgot to open this.

I will open this now.

**Comment by jiggzson** [comment]
@Happypig375, I've added support for gcd with a variable number of parameters but you seem to have put in much more work beyond that into this issue with this PR. 

All I did is build on the fact that gcd(a, b, c) = gcd(a, gcd(b, c)). Honestly that's all I though you were going to do.

 It seems you've already resolved the conflicts so I don't think you need to pull any changes at this point but I haven't reviewed your changes yet. 

You're still failing tests so let me know how to help so we can close this PR. I'm in the process of wrapping up partial fractions so I'll be able  to help if you need me to.

**Comment by Happypig375** [comment]
>I've added support for gcd with a variable number of parameters but you seem to have put in much more work beyond that into this issue with this PR.

>All I did is build on the fact that gcd(a, b, c) = gcd(a, gcd(b, c)). Honestly that's all I though you were going to do.

I am doing #332 in parallel. When none of the variables repeatedly appear, e.g. gcd(a^a,b^c,d*e,f(g)), then it does not evaluate. That is what Wolfram Alpha does.

>It seems you've already resolved the conflicts so I don't think you need to pull any changes at this point but I haven't reviewed your changes yet.

And now every time a new commit is on dev, a new merge conflict appear. I will try to finish this within the next days.

>You're still failing tests so let me know how to help so we can close this PR. I'm in the process of wrapping up partial fractions so I'll be able to help if you need me to.

https://github.com/jiggzson/nerdamer/pull/337#issuecomment-353816129

**Comment by Happypig375** [comment]
Argh I can't figure out the cause https://github.com/jiggzson/nerdamer/pull/337#issuecomment-353816129 today. Maybe tomorrow...

**Comment by jiggzson** [comment]
@Happypig375, That shouldn't happen. I'll look into this.

**Comment by jiggzson** [comment]
@Happypig375, above mentioned issue has been fixed. The problem was due to a comparison from way back when powers were still stored as integers. Between this and the sqrt problem, I'm amazed that this hasn't surfaced before.

**Comment by Happypig375** [comment]
The CI build log is... "helpful".

**Comment by Happypig375** [comment]
Closing and reopening to re-test.

**Comment by Happypig375** [comment]
Now this CI build log is helpful.

**Comment by Happypig375** [comment]
`nerdamer("3/a").symbol.getNum()` => 3
`nerdamer("3/a").symbol.getDenom()` => 3*a^(-1)

!?!?!?!?!?!?

**Comment by Happypig375** [comment]
`nerdamer("1/3").symbol.getDenom()` => 3
`nerdamer("1/a").symbol.getDenom()` => a^(-1)

Inconsistent behavior...

**Comment by jiggzson** [comment]
>Inconsistent behavior...

Yes. And this isn't the only method that does this. A lot of these methods morphed into something else and keep morphing as the library gets more complex. At the time of its creation I needed that behavior but I should have given a bit more thought to it. If your code is relying on this then we can either clean it up or you can work with its current quirks and I'll clean it up later. Let me know.

**Comment by Happypig375** [comment]
Yep, I am going to depend on getNum and getDenom.
They should be standardized so that I can do the same stuff with Numbers and Symbols.
Preferably, nerdamer("1/a").symbol.getDenom() => a
I am not going to work around this for now because the workaround will need a lot of hacky code.

https://github.com/jiggzson/nerdamer/pull/337#issuecomment-356253716 is a bug either way so that should be fixed.

**Comment by jiggzson** [comment]
Agreed. Additionally 2*a should be returned when calling getDenom for  (1/2)*a^(-1). I may have to go the the route of creating a getDenominator and getNumerator method if changing getDenom proves to difficult.

**Comment by jiggzson** [comment]
@Happypig375, both methods should now be fixed and the behavior more consistent. Keep in mind that for something like "1+1/x" it will return 1.

**Comment by Happypig375** [comment]
Still bugs to fix...
```js
document.writeln(_.parse("2/a").getDenom()); //2*a

**Comment by Happypig375** [comment]
`_.parse("1/2").getDenom() instanceof core.Symbol` => false
`_.parse("1/2").getDenom() instanceof core.bigInt` => true

Intended?

**Comment by jiggzson** [comment]
@Happypig375, the getDenom issue has been fixed.

**Comment by Happypig375** [comment]
@jiggzson Are you talking about the commit ca019ddffc0d0f38ba0fd66763593c9b5c9be040? I don't see that commit modify the nerdamer.core.js file and the issue is still not fixed.

**Comment by jiggzson** [comment]
@Happypig375, fixed.

**Comment by Happypig375** [comment]
Retest

**Comment by Happypig375** [comment]
I don't get why the CI build keeps complaining about `TypeError: Cannot read property 'group' of undefined`.
When I copy core.js and Algebra.js from my branch into https://jsbin.com/?js,console and enter `console.log(nerdamer("gcd(2*x^2+2*x+1,x+1)").toString())`, there is no error and "1" is outputted correctly.

**Comment by Happypig375** [comment]
`console.log(nerdamer("1/2").symbol.getNum().toString());` => 1/2
Still more bugfixing needed

**Comment by jiggzson** [comment]
@Happypig375, It's fixed this time. Promise.

**Comment by Happypig375** [comment]
Forcing tests to pass for now even when there are a bit of inconsistency in gcd and lcm in handling arguments that have no duplicating variables, but I think that no one will notice.

Okay to merge?

Bye bye the repo's longest thread - 70 comments - but now this journey must come to an end. Goodbye #337. 😢

**Comment by jiggzson** [comment]
@Happypig375, try running `integrate(x*e^x, x)`. It passes on dev and hangs on yours.

**Comment by Happypig375** [comment]
Umm... So how did the tests pass? Will look tomorrow.

**Comment by Happypig375** [comment]
How is that hanging?
I see that integrate does not even call gcd.

**Comment by jiggzson** [comment]
> Umm... So how did the tests pass?

That's the crazy part. It's probably something minor. I'll try to get to this today. The weird part is that it computes just fine when I pop it into nerdamer but hangs during the test.

**Comment by jiggzson** [comment]
@Happypig375, I think the reason is that you haven't fully pulled all the changes from dev in to patch-7. 
Like here
[patch-7](https://github.com/Happypig375/nerdamer/blob/d9477f5f0ed1c039278411e0538cfa6e6700af3b/nerdamer.core.js#L4989)
[dev](https://github.com/jiggzson/nerdamer/blob/8ebdc89f789d06b385b88d1a260dae6dc158978a/nerdamer.core.js#L4995)
It's a major change that will cause a bunch of tests to fail. This is the change that I mentioned in #285 regarding the switch in toDecimal. Can you pull go ahead and pull all the changes from dev?

**Comment by Happypig375** [comment]
Bye 77-comment post.
Was fun working with you. Now bye~~~~~ 😭

**Comment by Happypig375** [comment]
Actually a TODO is left here:
gcd(a^a,a^(a-1)) => a should=> a^(a-1)

My implementation for gcd of EX is mainly targetted for gcd(2^a,6^a) => 2^a

And Wolfram Alpha gives gcd(2^a,6^(a-2)) => 2^(a-2)/9

What!?

**Comment by jiggzson** [comment]
@Happypig375, thanks. Merging.

**Comment by Happypig375** [comment]
>	jiggzson  merged 100 commits into jiggzson:dev from Happypig375:patch-7 43 minutes ago
100 commits... that number... so perfect...

Btw, will open issue regarding the todos of gcd.

**Comment by jiggzson** [comment]
:laughing: I notice that you have an affinity for perfect numbers. Thanks for all the work you put in.

**Comment by Happypig375** [comment]
:smile:
Btw, I don't like how GitHub gives away the Contributor tag.
Only people who commit to a repo's master branch and gh-pages branch or PR to these two branches are merged are rewarded with the Contributor tag.
This is in direct opposition to organized development using development branches.
Before nerdamer used dev branch: all people whose PR to master get merged are rewarded with the Contributor tag.
After nerdamer used the dev branch: PRs to dev branch do not count as contributions.

Wtf GitHub!? :rage:
This is discrimination.

**Comment by jiggzson** [comment]
We should Google this. It might have to do with squash-and-merge. Worst case do at least one contribution directly to master. Your contributions have been massive and I'll make sure to mention this in the README me file.

Thanks for all your work. I really appreciate it.

**Pull request merged**
