### PR TITLE
ConvertToLaTeX tweak

### PR DESCRIPTION
**Pull request by gksander**
A few minor tweaks/additions to convertToLaTeX function.

### CODE REVIEW

**Comment by gksander** [comment]
Whoops -- two of my testing files snuck into this PR. Disregard prepros-6.config and test.html.

**Comment by jiggzson** [comment]
Thanks! Is this ready to merge?

**Comment by gksander** [comment]
Yep -- it's good to go.

**Comment by jiggzson** [comment]
Awesome.

**Pull request merged**
