### PR TITLE
Fixes #307 and #313

### LINKED ISSUE #307: Problem with toTeX()
In 0.7.12 the following code ran without issues:

`
var a=nerdamer("vector(1,2,3)");              
console.log(a.toTeX());
` 

Using 0.7.13 it returns an error: 

`nerdamer.core.js:5820 Uncaught TypeError: symbol.clone is not a function
    at Object.latex (nerdamer.core.js:5820) ...
`

### PR DESCRIPTION
**Pull request by menzelths**
Two small bugfixes which make nerdamer even better :-)

Fixes #307 and #313

### CODE REVIEW

**Comment by Happypig375** [comment]
You should request to marge into dev branch because that is where new development is done, and will be merged into master when appropriate.

**Comment by jiggzson** [comment]
@menzelths thanks for the PR. As @Happypig375 stated, the PR goes to dev during development. There was a reason for the clearVars fix since this issue came up in #55. Since then @ljacqu switched up to CI and I forgot to ask him to set up a test for this. Can you verify that this issue didn't pop up again with the current solution. I'd appreciate that.

**Comment by menzelths** [comment]
PR for dev at #315

**Comment by menzelths** [comment]
@jiggzson I tested #55 and I see three lines as expected.
I get 

  1
  x=1
  1

Looks good to me.

**Comment by menzelths** [comment]
By the way, just to show you, what I use nerdamer for:

https://menzelths.github.io/Mathematik-Kursstufe/Analytische_Geometrie_Abstand_windschiefe_Geraden.html#tags_@

All math was calculated and printed with nerdamer (I changed the vector-output to vertical stacks as it is common in Germany). The whole document was created with an online javascript editor that I wrote.

**Comment by jiggzson** [comment]
Really nice! My translate picked up the presentation but not the site. I can't tell where the dynamic calculations are being done since I speak Dutch and not German. Can I add this to the list of projects that use the library?

**Comment by ljacqu** [comment]
> Since then @ljacqu switched up to CI and I forgot to ask him to set up a test for this. 

A test for
```javascript
console.log(nerdamer.solveEquations("x+1=2", "x").toString())
console.log(nerdamer("x=1").text("fractions"))
console.log(nerdamer.solveEquations("x+1=2", "x").toString())
```

Or what are we talking here?

> since I speak Dutch

Wat een verrassing! Ik dacht altijd dat je in de VS zat (of zo), aangezien je Engels zo naaturlijk klinkt.

**Comment by jiggzson** [comment]
@ljacqu lol. Jawel. Ik woon wel in VS. I've been here for a very long time so my Dutch is weak as far as speaking. But I understand it 100%. I didn't know you were Dutch lol.

**Comment by jiggzson** [comment]
@menzelths. I merged the other PR so I'm closing this one.

**Comment by menzelths** [comment]
Thank you for merging this fast :-)

Answering your question about my project: you are welcome to mention it.

About the dynamical calculationL it is done during content creation. If you want a look behind the scenes:

https://menzelths.github.io/Mathematik-Kursstufe/example.html

Nerdamer is omnipresent, all math is done by your library. Kudos!

Take a look at http://menzelths.github.io to find the collection of everything created up to now. The editor itself can be found at https://menzelths.github.io/TshareWriterLatest/TShare.html, documentation is still pending but will follow soon.

The somewhat chaotic repository can be found here: https://github.com/menzelths/TshareWriterLatest

**Comment by ljacqu** [comment]
@jiggzson You flatter me :) I'm just a Swiss who learned Dutch ;)

I definitely think it's worth writing a test for this, in fact I'd say writing a test for every bug that appears is worth it because that's way it's covered with a test for eternity. I'll send a PR, even if it's nothing big to do.

**Comment by jiggzson** [comment]
@ljacqu your contributions are always appreciated. Thank you for writing the tests. I get so caught up in the bug hunt at times that stopping to write tests just feels like a nuisance even though it's very crucial.

**Pull request closed without merging**
