### PR TITLE
**DO NOT MERGE** Test run with useAlgebraDiv()

### PR DESCRIPTION
**Pull request by Happypig375**
See https://github.com/jiggzson/nerdamer/pull/316#issuecomment-347465991.

### CODE REVIEW

**Comment by Happypig375** [comment]
Tests ran, closing.

**Comment by Happypig375** [comment]
Oops, test results are gone! Reopening.

**Comment by jiggzson** [comment]
You don't have to create a PR to see if your tests fail. Just install [**node.js**](https://nodejs.org/en/download/) which installs npm. Install [**jasmine**](https://www.npmjs.com/package/jasmine). Navigate to the nerdamer directory and then run the command **jasmine**. If you're in a windows environment you'll see two tests fail but ignore those. They're just rounding errors. If you're in a Linux environment you should not have any failed tests.

**Comment by ljacqu** [comment]
You could open PR's on your own fork though, just need to set up CircleCI. Because for me it's _inconvenient_ to be getting a notification because you want to run tests ;)

**Comment by jiggzson** [comment]
@Happypig375  can you close this PR? @ljacqu gave a mobile solution for checking tests.

**Comment by Happypig375** [comment]
Technically this PR is like an issue but with failing tests. You see, even basic arithmetic operations fail under useAlgebraDiv(). Should I make this an actual issue?

**Comment by jiggzson** [comment]
**useAlgebraDiv** is a huge compromise. As I've been saying from day one, making the divide operator behave as the divide function is tremendously difficult because of circular dependencies. Anything beyond **useAlgebraDiv** would require rewriting the entire library. If it was that simple I wouldn't have opted for yet another function.

**Comment by Happypig375** [comment]
Move to #354

**Pull request closed without merging**
