### PR TITLE
Version 0.7.2

### PR DESCRIPTION
**Pull request by jiggzson**

### CODE REVIEW

**Comment by jiggzson** [comment]
Summoning @ljacqu 
It seems I have a lot of test failing. I think it has to do with the fact that solve now return 'pi' in instead of the value of pi and the fact that the factorial function was renamed from 'fact' to 'factorial'. Issue #76 was fixed with the parser rebuild. Additionally I would like to the add the following tests to the core tests
```javascript
var cases = {
    '0-4': {
        expected: '-4'
    },
    '-(4)': {
        expected: '-4'
    },
    '3*-(4)': {
        expected: '-12'
    },
    '-3*-(4)': {
        expected: '12'
    },
    '-(3*-(4))': {
        expected: '12'
    },
    '-(-3*-(4))': {
        expected: '-12'
    },
    '-(3)-3': {
        expected: '-6'
    },
    '3^-1^-1': {
        expected: '1/3'
    },
    '-1': {
        expected: '-1'
    },
    '--1': {
        expected: '1'
    },
    '8-1': {
        expected: '7'
    },
    '(-1)': {
        expected: '-1'
    },
    '-(1)-1': {
        expected: '-2'
    },
    '-(-1-1)': {
        expected: '2'
    },
    '-(-1-+1)^2': {
        expected: '-4'
    },
    '-(-1-1+1)': {
        expected: '1'
    },
    '-(1)--(1-1--1)': {
        expected: '0'
    },
    '-(-(1))-(--1)': {
        expected: '0'
    },
    '5^-3': {
        expected: '1/125'
    },
    '5^---3': {
        expected: '1/125'
    },
    '5^-(1--2)': {
        expected: '1/125'
    },
    '5^-(++1+--+2)': {
        expected: '1/125'
    },
    '(5^-(++1+--+2))^-2': {
        expected: '15625'
    },
    '(5^-3^2)': {
        expected: '1/1953125'
    },
    '(5^-3^-2)': {
        expected: '5^(-1/9)'
    },
    '-(5^-3^-2)^-3': {
        expected: '-5^(1/3)'
    },
    '-(--5*--7)': {
        expected: '-35'
    },
	'-(1)--(1-1--1)': {
        expected: '0',
        evaluated_value: 0
    },
    '(-1)^(3/4)': { //to be added
        expected: '(-1)^(3/4)',
        evaluated_value: '(-1)^(3/4)'
    },
};
```
If you're able to I appreciate your help.

Thanks in advance.

**Comment by ljacqu** [comment]
Hi @jiggzson, absolutely! I'm in the process of moving right now, please allow me a few days to complete the task

**Comment by jiggzson** [comment]
No problem @ljacqu.

**Comment by jiggzson** [comment]
I'm hoping to start supporting expression substitution as well. These were some  of the tests I could think of. If you can think of a few more feel free to throw them in as well. Sorry if it's a little messy.
```javascript
var cases = [
    nerdamer('2*(x+1)^2').sub('x+1', 'u'), //expects -> 2*u^2
    nerdamer('2*(x+1+a)^2').sub('x+1', 'u'), //expects -> 2*(1+a+x)^2
    nerdamer('2*(x+1)^(x+1)').sub('x+1', 'u'), //expects -> 2*u^u
    nerdamer('2*(x+1)^2').sub('(x+1)^2', 'u^x'), //expects -> 2*u^(2*x)
    nerdamer('(2*(x+1)^2+a)^2').sub('(x+1)^2', 'u^x'), //expects -> (2*u^x+a)^2
    nerdamer('(2*(x+1)^2+a)^2').sub('(x+1)', 'u^x'), //expects -> (2*u^(2*x)+a)^2
    nerdamer('(x^x+y)^(x^x-t)').sub('x^x', '4'), //expects -> (4+y)^(-t+4)
    nerdamer('(cos(x)+cos(x)^2)').sub('cos(x)', '4'), //expects -> 20
    nerdamer('(cos(x)+cos(x)^2)').sub('(cos(x)+cos(x)^2)', '4'), //expects -> 4
    nerdamer('(cos(x)+cos(x^6)^2)').sub('(cos(x)+cos(x)^2)', '4'), //expects -> cos(x)+cos(x^6)^2
    nerdamer('(cos(x)+cos(x^6)^2)').sub('cos(x)', '4'), //expect -> 4+cos(x^6)^2
    nerdamer('(cos(x)+cos(x^6)^2)').sub('2', '4'), //expects -> error
];
```

**Pull request merged**
