### PR TITLE
Add more symbolic test cases to solver spec

### PR DESCRIPTION
**Pull request by AlienKevin**
I add some additional symbolic test cases for square root, trig functions, and natural logarithm. Tests for trig functions involve inverse trigs and the test results are all simplified. Some tests involve domain issues regarding different inverse trig functions.

### CODE REVIEW

**Comment by AlienKevin** [comment]
Sorry for messing up your master branch. Please tell me if I did some other things wrong.

**Comment by jiggzson** [comment]
@AlienKevin, thank you for this PR. I've been a little absent so thank you for your patience. I'm hoping to get to it in a few days.

**Comment by AlienKevin** [comment]
@jiggzson I'm happy to see Nerdamer back in development! 😄

**Comment by jiggzson** [comment]
@AlienKevin, glad to be back.

**Pull request merged**
