### PR TITLE
Try to fix #119

### LINKED ISSUE #119: Make divide() the / operator
Make it when the algebra module is loaded, replace / behaviour with divide(). Does not make sense to have a separate divide() function.

### PR DESCRIPTION
**Pull request by Happypig375**
An attempt at my original first issue (#119), which response was what kept me here. I think that if I let this issue stay, it will not go anywhere. Bye first issue 😈

### CODE REVIEW

**Comment by Happypig375** [comment]
Oooh, revealed a lot of divide bugs at the same time 😆

**Comment by Happypig375** [comment]
I'd expect this PR to stay open for quite a while 😉

**Comment by jiggzson** [comment]
This issue is quite complicated then you probably imagine. The biggest problem is that Algebra.divide depends on Parser.divide so swapping it will result in an infinite loop. One solution might be to keep track of where you are on the stack by placing a dummy on it like I did [here](https://gist.github.com/jiggzson/30ebef4a7bf97d2412964ff1b11938b5).

**Comment by Happypig375** [comment]
No, I did it not by replacing Parser.divide but telling the operator / to go to Algebra.divide. Not sure why the tests are failing though, probably bugs in Algebra.divide.

**Comment by Happypig375** [comment]
Speaking of the logger, what do you think of integrating it into the library itself?

**Comment by Happypig375** [comment]
CI build (line 604 of build log):
>
7) Nerdamer core Further arithmetic test cases Batch 1
  Message:
    Expected 'x+x^(-1)*y' to equal 'x*y'.
  Stack:
    Error: Expected 'x+x^(-1)*y' to equal 'x*y'.
        at Object.<anonymous> (/home/travis/build/jiggzson/nerdamer/spec/core.spec.js:1716:43)

Yup, bugs confirmed.

**Comment by jiggzson** [comment]
Not really

```javascript
var x = nerdamer.divide('y', 'x');
console.log(x.toString()); 
//x^(-1)*y
```

As I said the before. Arbitrarily changing the divide method will eventually result in it calling itself with disastrous results. I'm quite sure that's what's happening.

**Comment by Happypig375** [comment]
>arbitrarily changing the divide method 

I changed the operator only, not the function. I'm confused.

**Comment by jiggzson** [comment]
You changed the method that it maps to. So here's an possible example.

You call **x/y** which then calls **Algebra.divide** which then calls **Parser.divide** but **Algebra.divide** is now **Parser.divide** so we have a recursive call. The overridden method wanted to call **Parser.divide** instead of itself. Had you created some way to know who was doing the calling and provided it to the method then it would have been able to make that choice and terminate the loop. Is that clear?

**Comment by Happypig375** [comment]
Algebra.divide is now Parser.divide so we have a recursive call.

Nonono, look at the changes in this PR. The first line defines a *new* "divide+-\*/Algebra" in parser. The second line sets the underlying function of the / operator (the division operator, not the divide function of parser) to the newly created "divide+-\*/Algebra". What does "divide+-\*/Algebra" do? It points to Algebra.divide. Then Algebra.divide calls Parser.divide. Notice how Parser.divide is untouched. When it is untouched, no loops occur, so the problem you mentioned does not occur.

So the logic is this:
x/y => Parser."divide+-\*/Algebra"(x,y) => Algebra.divide(x,y) => Parser.divide(x,y)

**Comment by jiggzson** [comment]
It does. Look at the source code for **Algebra.div**. This is where the recursive call occurs since **Algebra.divide** depends on **Algebra.div** which depends on Parser.divide.

**Comment by Happypig375** [comment]
Continue tomorrow, I need to sleep now, bye

**Comment by jiggzson** [comment]
Closing. Will re-open after branch reset.

**Comment by jiggzson** [comment]
I

**Comment by jiggzson** [comment]
I think I may I have found a solution to the issue. As I stated before. Use at your own risk since this may have unintended consequences, but I'm sure you'll let me know if that happens :) This solution was inspired by our earlier discussion to use the same logic as the stepper. It basically checks if the call being made is the first call, and if it is, it uses Algebra.divide. If not it uses PARSER.divide. You have to first call the **useAlgebraDiv** function to activate it and if you want to use the original divide function **useParserDiv** to deactivate it

```javascript
nerdamer.useAlgebraDiv();
var x = nerdamer('(x^2+2*x+1)/(x+1)');
console.log(x.toString()); //1+x
nerdamer.useParserDiv();
var x = nerdamer('(x^2+2*x+1)/(x+1)');
console.log(x.toString()); //(1+2*x+x^2)*(1+x)^(-1)
```

**Comment by jiggzson** [comment]
@Happypig375 have you tried the solution yet?

**Comment by Happypig375** [comment]
I am busy these two days so maybe until Sunday I can try it out (Note: my time zone is +0800)

**Comment by Happypig375** [comment]
@jiggzson This is ok on first look, see #326 for running tests with this on.

**Comment by Happypig375** [comment]
Implemented, closing.

**Comment by Happypig375** [comment]
(x^2-x\*y)/(x\*y-y^2) => JavaScript error: Uncaught RangeError: Maximum call stack size exceeded on line 10082

**Pull request closed without merging**
