### PR TITLE
Calculus tweaks

### PR DESCRIPTION
**Pull request by gksander**
Functionality for definite integration.

Minor LaTeX patches.

### CODE REVIEW

**Comment by gksander** [comment]
I'm adding a defint (definite integral) function, which is helpful for quick classroom-computations. However, I have a couple questions before merge:

1. The function is basically just piggy-backing off of integrate in cases where the function can be handled symbolically. However, I'd like to do some numerical approximation in cases where the function cannot be integrated symbolically. I'm still thinking about this. Any thoughts on preferred quadrature/integration techniques? 

2. Would you prefer the function to be called defint or defintegrate? The latter provides more consistency with the integrate command, but the former is more concise. I'm happy to go with either one.

**Comment by jiggzson** [comment]
Thanks a lot for the addition. I'm pretty much an agnostic when it comes to which technique to use. I often find myself having to use a combination of different techniques due to some of the limitations of JavaScript so I'm 100% good with your choice. My preference is to use **defint**. We can always alias that. I'm not sure but I did that with diff in the Calculus package.

I was looking at your commit and I just wanted to point out that you can just call integrate directly using

```javascript
var sym = __.integrate(expr, dx);
```
The input already comes as a Symbol and when inside of the package the double underscore refers to the current package so you can use the methods directly.

**Comment by jiggzson** [comment]
I just realized that the hasIntegral had a bug. I'm going to fix it right now so the above mentioned example is still good. Is this PR still ongoing? I started to put together **[this](https://gist.github.com/jiggzson/ccc4ec0c93cbacfea40c66e2456c5d95)** function but the problem becomes finding discontinuities over the interal. Do you have a good method for detecting those prior to calculating the integral? I read somewhere that one method is to look for huge spikes. Any thoughts?

**Comment by gksander** [comment]
Sorry -- I got a little busy the past week or two, so haven't had time to make any progress on this. You can actually merge this PR if you want and delete/redo/tweak the defint function, or just manually make the changes that I suggested from the PR. I'm sure you'll make progress on the defint function quicker than I will (the defint.js file you linked is looking good).

As for discontinuities... I'm not really sure. "Huge spikes" sounds reasonable, but I'm not sure what the implementation would like like. I guess the first thing that pops into my mind is crudely testing a limit at a point, something like
```
Math.abs(f(x-0.00001)-f(x+0.00001)) < epsilon
```
Or one might make that relative like
```
Math.abs(f(x-0.00001)-f(x+0.00001))/Math.abs(f(x-0.00001)) < epsilon
```
This would reasonably eliminate jump discontinuities, which I imagine are the biggest issue when integrating. But I haven't thought much about this, so I'm not sure if that would be a reasonable approach.

**Comment by jiggzson** [comment]
This shows some promise. 
```javascript
var f = Math.tan;
var x = Math.PI/2;
console.log(Math.abs(f(x-0.00001)-f(x+0.00001))); //199999.9999920231
x = Math.PI/2+0.1;
console.log(Math.abs(f(x-0.00001)-f(x+0.00001))); //0.002006680041207076
```
I'll play around with it some more.

**Pull request merged**
