### PR TITLE
#363 reborn

### PR DESCRIPTION
**Pull request by Happypig375**
#363 reborn

### CODE REVIEW

**Comment by Happypig375** [comment]
@jiggzson 
Milestone!
The CI build number is the same as the PR number!

**Comment by Happypig375** [comment]
YAY PASSING TESTS :tada: :tada:

**Comment by jiggzson** [comment]
@Happypig375, thanks for the commit but what is the reason for changing the tests from trig to hyperbolic trig? I'm confused.

**Comment by Happypig375** [comment]
In core.spec.js, there are the trig tests:
https://github.com/jiggzson/nerdamer/blob/2e5849fd1cd33340594b632ca594742d6c0ff5b3/spec/core.spec.js#L656
and the hyperbolic trig tests:
https://github.com/jiggzson/nerdamer/blob/2e5849fd1cd33340594b632ca594742d6c0ff5b3/spec/core.spec.js#L922

But, the hyperbolic trig tests use normal trig functions, resulting in duplicate tests:
(Lines 818 to 832)
https://github.com/jiggzson/nerdamer/blob/2e5849fd1cd33340594b632ca594742d6c0ff5b3/spec/core.spec.js#L818-L832
(Lines 1019 to 1033)
https://github.com/jiggzson/nerdamer/blob/2e5849fd1cd33340594b632ca594742d6c0ff5b3/spec/core.spec.js#L1019-L1033

I am fixing the hyperbolic trig ones so that the tests are not duplicated.

**Comment by jiggzson** [comment]
Got it. Thanks. Merging.

**Pull request merged**
