### PR TITLE
Update expected results (closes #74)

### LINKED ISSUE #74: Failing tests
Hello, the result of the following tests has changed. Could I ask you to confirm that the new results are correct?

```
given: 'integrate(x*asin(x), x)',
expected: '(-1/4)*asin(x)+(1/2)*asin(x)*x^2+(1/4)*sqrt(-x^2+1)*x'
actual:   '(-1/4)*asin(x)+(1/2)*asin(x)*x^2+(1/4)*cos(asin(x))*sin(asin(x))'

given: 'integrate(q/((2-3*x^2)^(1/2)), x)',
expected: 'asin(sqrt(2)^(-1)*sqrt(3)*x)*q*sqrt(3)^(-1)'
actual:   'asin(3*sqrt(6)^(-1)*x)*q*sqrt(3)^(-1)'

given: 'integrate(x*(x+a)^3, x)',
expected: '((1/4)*x^4+(3/2)*a^2*x^2+a*x^3+a^3*x)*x+(-1/2)*a^2*x^3+(-1/2)*a^3*x^2+(-1/20)*x^5+(-1/4)*a*x^4'
actual:   '(1/2)*a^3*x^2+(1/5)*x^5+(3/4)*a*x^4+a^2*x^3'

given: 'integrate(8*x^3/(6*x^2+3*a^2), x)',
expected: '8*((-1/24)*a^2*log(3*a^2+x^2)+(1/12)*x^2)'
actual:   '8*((-1/24)*a^2*log(2*x^2+a^2)+(1/12)*x^2)'

given: 'integrate(log(a*x+b),x)',
expected: '((a*x+b)*log(a*x+b)-a*x-b)*a^(-1)'
actual:   '-x+a^(-1)*b*log(a*x+b)+log(a*x+b)*x'

given: 'integrate(t*log(x)^3,x)',
expected: '(-3*log(x)^2+6*log(x)+log(x)^3-6)*t*x'
actual:   '(-3*log(x)^2*x-6*x+6*log(x)*x+log(x)^3*x)*t'

given: 'integrate(5*x*e^(-8*a*x^2),x)',
expected: '(-5/16)*a^(-1)*e^(-8*a*x^2)*log(e)^(-1)'
actual:   '(-5/16)*a^(-1)*e^(-8*a*x^2)'

given: 'integrate((x+7)/(x+1)^3,x)',
expected: '(-1/2)*(1+x)^(-1)+(-1/2)*(1+x)^(-2)*(7+x)'
actual:   '(-1/2)*(1+x)^(-1)+(-7/2)*(1+x)^(-2)+(-1/2)*(1+x)^(-2)*x'
```

### PR DESCRIPTION
**Pull request by ljacqu**

### CODE REVIEW

**Comment by ljacqu** [comment]
If you keep it open for a bit I will add more test cases.

**Comment by jiggzson** [comment]
No problem. Will do. I appreciate that.

**Comment by ljacqu** [comment]
That would be it! Thanks @jiggzson. I went through the old issues and added test cases for the bugs that were reported.

**Comment by jiggzson** [comment]
Ok. Cool. So I can close this PR?

**Comment by ljacqu** [comment]
Yes, please.

**Pull request merged**
