### PR TITLE
Patches: setFunction, pfactor, roots

### PR DESCRIPTION
**Pull request by gksander**
Some minor patches:

* after using setFunction, calls to that function weren't working.
* pfactor()'s latex() method was raising errors.
* roots function was returning vector, and latex() method wasn't handling it.

gcd()'s latex() method is also causing some problems, but I'm having troubles tracking that down.

### CODE REVIEW

**Comment by jiggzson** [comment]
What are the problems caused by the gcd latex function? Maybe I can help track it down. Also with the last commit you added the file 'prepros-6.config'. Do we need this? If not can it be removed?

**Comment by gksander** [comment]
If you run `nerdamer('gcd(10,15)').toTeX()` in the console, you'll get the error stack. Looks like issues with a .lessThan() call. I'm still figuring out the inner workings of the core, so it takes me awhile to figure out where the issues are rooted. I'm not sure if it's rooted in the actual gcd function or not.

Whoops. Yes, prepros-6.config and testing.html accidentally snuck into that pull request. Those weren't supposed to make it to the remote branch (they're just two files I'm using to develop/test locally).

**Comment by jiggzson** [comment]
The problem is that gcd isn't returning a Symbol for numeric values but rather a Frac object
around line 2083 it should be
```javascript
if(a.isConstant() && b.isConstant()) { 
        return new Symbol(core.Math2.QGCD(new Frac(+a), new Frac(+b)));
}
```
instead of 
```javascript
if(a.isConstant() && b.isConstant()) { 
        return core.Math2.QGCD(new Frac(+a), new Frac(+b));
}
```
I noticed that in your PR around line 2700 in the core you change
```javascript
retval = fn.apply(fn, args);
```
to 
```javascript
retval = fn.apply(fn_settings[2], args);
```
but fn_setting[2] is undefined. The variable _fn_ is to have **this** within the function's scope. Was this causing problems?

**Comment by gksander** [comment]
Okay, nice -- that works. I added that in on a commit on this PR.

As for Line 2700 of the core -- a property/method call on fn was returning undefined when trying to make a function call after defining a function. It looked like the method trying to be accessed was stored in fn_settings[2] rather than fn. For example, after calling `nerdamer.setFunction('f', ['x'], 'x^2')` and then trying to call `nerdamer('f(13)')`, that line was raising an error. (This is present in your demo in the current docs.) 

I made the switch to fn_settings[2] and that seemed to resolve the function issue, and I tested it with most of the other functions and I didn't get thrown any errors. Admittedly, I'm not totally sure why it worked -- I just worked down the error stack and noticed that a property wasn't found on the fn object, but was part of the fn_settings[2] object.

**Comment by jiggzson** [comment]
I recently rewrote the core parser and I missed that during the rewrite. In the case of setFunction, the _.mapped_function method is supposed to set the function on the fly and I forgot the make that connection. I'll go ahead and close this PR and I'll fix that issue soon.

**Comment by jiggzson** [comment]
Wow you were spot on with your setFunction fix. I actually completely forgot that that's how I link back to setFunction. Thanks!

**Pull request merged**
