### PR TITLE
Support for Product LaTeX, solver toLHS

### PR DESCRIPTION
**Pull request by gksander**
Support for product() LaTeX.

solver's toLHS method was expecting string, but getting fed an Equation
object. Altered slightly to keep it from throwing errors.

### CODE REVIEW

**Comment by gksander** [comment]
The Solve.js `solve` method was throwing errors when passing equations (but was working for expressions). For example, `nerdamer('solve(x+1=2, x)')` would throw an error, due to the toLHS method. It looks like maybe along the way, equations used to be strings -- but an Equation class was created? Nevertheless, altering the toLHS method slightly fixed these errors.

I noticed though that trying to solve a system of equations returned 0 every time. I didn't get a chance to look into why that is.

**Comment by jiggzson** [comment]
To solve a system of linear equations the set of equations has to be an array. So

```javascript
var solutions = nerdamer.solveEquations(['x+y=2', '2*x-y=7']);
```
Is that what you're passing in? As for the

```javascript
var solution = nerdamer('solve(x+1=2, x)');
```
That is indeed a bug. I'll make sure to fix it. Currently your PR is failing all CI tests.

**Comment by jiggzson** [comment]
I made a correction to your PR in the Solve.js file. This was causing all your tests for solve to fail. Let me know if this PR is done. I can leave it open for a little bit if you have anything else that you're planning to add.

**Comment by gksander** [comment]
Awesome -- thanks! You can merge, I don't think I'll have time to add anything to this in the next couple of days. 

I was trying to use `nerdamer('solve[x+y=2, 2*x-y=7])')` instead of the `nerdamer.solveEquations` method. 

As for the CI tests -- I just now noticed you added a spec folder and Jasmine. I'll make sure to start running `npm test` before making PR's! I've never used Jasmine, so this should be a good learning experience.

**Pull request merged**
